POST http://localhost:4004/admin/addProductCategory
Content-Type: application/json

{
    "payload": [{
    "ID": 15,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}

####

POST http://localhost:4004/admin/addProducts
Content-Type: application/json

{
    "payload": [{
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    },
    {
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    },
    {
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    },
    {
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    }]
}

####
POST http://localhost:4004/orders/sendOrder
Content-Type: application/json

{
    "payload": {
    "Status": "New",
    "Customer_ID": 1,
    "OrderItems": [
        {
            "Product_ID": 1,
            "Quantity": 1,
            "Price": 12.99
        }
    ]
}
}