POST http://localhost:4004/admin/addProductCategory
Content-Type: application/json

{
    "payload": [{
    "ID": 14,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}

####

POST http://localhost:4004/admin/addProducts
Content-Type: application/json

{
    "payload": [{
    "ID": 14,
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    },
    {
    "ID": 51,
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    },
    {
    "ID": 109,
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 1
    },
    {
    "ID": 110,
    "Name": "test order 1",
    "Description": "this is a test entry",
    "Price": 18.99,
    "Stock": 20,
    "Category_ID": 13
    }]
}

####
POST http://localhost:4004/orders/sendOrder
Content-Type: application/json

{
    "payload": {
    "ID":3,
    "OrderDate":"2025-05-21T09:14:00Z",
    "Status": "New",
    "Customer_ID": 1,
    "OrderItems": [
        {
            "ID": 3,
            "Order_ID": 1,
            "Product_ID": 1,
            "Quantity": 1,
            "Price": 12.99
        }
    ]
}
}