POST http://localhost:4004/admin/addProductCategory
Content-Type: application/json

{
    "payload": [{
    "ID": 10,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}


####