POST http://localhost:4004/orders/addProductCategory
Content-Type: application/json

{
    "id": 3,
    "name": "test order 1",
    "description": "this is a test entry"
}


####

POST http://localhost:4004/orders/selectProductCategory
Content-Type: application/json

{
    "id": 1
}